// Demo Project Data for Film & Video Production Prep (CinePrep)
const DEFAULT_PROJECT = {
  id: "proj_tvc_aura_2026",
  title: "Aura Coffee - 'Awaken The Senses'",
  type: "Commercial (TVC & Digital)",
  client: "Aura Beverages Inc.",
  agency: "Creative Pulse Studio",
  productionCompany: "Nusantara Cinema Lab",
  director: "Arya Pratama",
  producer: "Maya Siregar",
  firstAD: "Budi Santoso",
  dop: "Reza Rahardian",
  currentDay: 1,
  totalDays: 2,
  shootDate: "2026-10-15",
  weather: "Partly Cloudy, 28°C - 32°C. 15% rain chance.",
  sunrise: "05:25 AM",
  sunset: "17:45 PM",
  generalCall: "06:00 AM",
  locationName: "Studio 4 & Roastery Cafe",
  locationAddress: "Jl. Suryo No. 42, Senopati, Kebayoran Baru, Jakarta Selatan",
  parkingNotes: "Gedung Parkir Belakang (Gate B). Voucher dibagikan oleh tim Unit.",
  hospitalName: "RS Siloam Semanggi (IGD 24 Jam)",
  hospitalAddress: "Jl. Garnisun 1 No. 2-3, Karet Semanggi, Setiabudi, Jakarta Selatan",
  hospitalPhone: "(021) 2996-2888 / 1500-181",
  scenes: [
    {
      id: "sc_1",
      sceneNumber: "1",
      slugline: "INT. COFFEE ROASTERY - MORNING",
      setting: "INT",
      timeOfDay: "MORNING",
      location: "Roastery Cafe Bar",
      pages: "1 2/8",
      synopsis: "Barista menyiapkan biji kopi pilihan dan menyeduh dengan V60. Uap harum mengepul di bawah cahaya pagi dramatis.",
      cast: ["Dimas Anggara (Barista)", "Tara Basro (Sarah)"],
      props: ["V60 Ceramic Dripper", "Artisan Glass Carafe", "Biji Kopi Roast Khusus", "Kettle Gooseneck Tembaga"],
      wardrobe: ["Apron Kulit Cokelat Vintage", "Linen Shirt Krem"],
      fx: ["Hazer Atmospheric Smoke Halus", "Macro Diopter Filter"],
      notes: "Prioritaskan shot macro slow-motion uap dan tetesan air."
    },
    {
      id: "sc_2",
      sceneNumber: "2",
      slugline: "EXT. CITY SIDEWALK - DAY",
      setting: "EXT",
      timeOfDay: "DAY",
      location: "Pedestrian Crossing Senopati",
      pages: "6/8",
      synopsis: "Sarah berjalan di trotoar kota yang ramai menikmati iced latte. Ekspresinya segar di tengah hiruk pikuk pagi.",
      cast: ["Tara Basro (Sarah)", "5x Pedestrian Extras"],
      props: ["Cup Takeaway Branded Aura", "Modern Leather Tote Bag"],
      wardrobe: ["Smart Casual Blazer Abu & White Sneakers"],
      fx: ["Reflector Sunbounce 4x4", "Gimbal Stabilizer Rig"],
      notes: "Izin jalanan sudah siap. Pasang traffic cone untuk jalur tracking gimbal."
    },
    {
      id: "sc_3",
      sceneNumber: "3",
      slugline: "INT. CREATIVE AGENCY OFFICE - AFTERNOON",
      setting: "INT",
      timeOfDay: "AFTERNOON",
      location: "Studio 4 - Set Ruang Rapat",
      pages: "2 1/8",
      synopsis: "Tim kreatif tampak jenuh berdiskusi di ruang meeting. Sarah masuk membawakan paket kopi, suasana seketika hidup dan produktif.",
      cast: ["Tara Basro (Sarah)", "Reza (Kreatif 1)", "Dina (Kreatif 2)", "Fahri (Client Lead)"],
      props: ["Coffee Carrier Box 4 Cups", "Laptops", "Sticky Notes & Whiteboard Spidol"],
      wardrobe: ["Casual Agency Attire"],
      fx: ["Warm Keylight Tungsten Look"],
      notes: "Setup lighting ruang rapat harus kontras sebelum dan sesudah kopi datang."
    }
  ],
  shots: [
    {
      id: "shot_1a",
      sceneId: "sc_1",
      shotNumber: "1A",
      size: "Extreme Close-Up (ECU)",
      angle: "Low Angle",
      movement: "Slow Push-In",
      lens: "100mm Macro f/2.8",
      fps: "60 fps",
      status: "Planned",
      description: "Tetesan air panas jatuh ke bubuk kopi, blooming mekar perlahan."
    },
    {
      id: "shot_1b",
      sceneId: "sc_1",
      shotNumber: "1B",
      size: "Medium Close-Up (MCU)",
      angle: "Eye Level",
      movement: "Pan Right",
      lens: "50mm Prime f/1.4",
      fps: "24 fps",
      status: "Planned",
      description: "Barista tersenyum fokus menuang kettle dengan presisi."
    },
    {
      id: "shot_1c",
      sceneId: "sc_1",
      shotNumber: "1C",
      size: "Over-the-Shoulder (OTS)",
      angle: "Eye Level",
      movement: "Static",
      lens: "35mm Prime",
      fps: "24 fps",
      status: "Planned",
      description: "Dari balik bahu Sarah menatap cangkir kopi pertama hari itu disajikan."
    },
    {
      id: "shot_2a",
      sceneId: "sc_2",
      shotNumber: "2A",
      size: "Medium Shot (MS)",
      angle: "Low Angle",
      movement: "Tracking Forward (Gimbal)",
      lens: "35mm f/1.8",
      fps: "48 fps",
      status: "Planned",
      description: "Sarah berjalan santai ke arah kamera, minum dengan sedotan ramah lingkungan."
    },
    {
      id: "shot_2b",
      sceneId: "sc_2",
      shotNumber: "2B",
      size: "Wide Shot (WS)",
      angle: "High Angle",
      movement: "Jib / Crane Down",
      lens: "24mm Ultra Wide",
      fps: "24 fps",
      status: "Planned",
      description: "Pemandangan jalanan kota berlatar gedung modern, Sarah tampak paling menonjol."
    },
    {
      id: "shot_3a",
      sceneId: "sc_3",
      shotNumber: "3A",
      size: "Master Wide Shot",
      angle: "Eye Level",
      movement: "Static",
      lens: "28mm Prime",
      fps: "24 fps",
      status: "Planned",
      description: "Suasana ruang rapat lesu, lalu pintu terbuka dan Sarah masuk tersenyum."
    },
    {
      id: "shot_3b",
      sceneId: "sc_3",
      shotNumber: "3B",
      size: "Close-Up (CU)",
      angle: "Eye Level",
      movement: "Handheld Subtle",
      lens: "85mm f/1.4",
      fps: "24 fps",
      status: "Planned",
      description: "Reaksi rekan kerja saat menerima cup kopi, menyeruput dan kembali bersemangat."
    }
  ],
  cast: [
    {
      id: "cast_1",
      castNumber: "1",
      characterName: "Sarah (Hero)",
      actorName: "Tara Basro",
      role: "Lead Talent",
      phone: "+62 811-2345-6789",
      pickupTime: "06:30 AM",
      hmuTime: "07:00 AM",
      onSetTime: "08:15 AM",
      notes: "Wardrobe fitting tuntas. Tidak ada alergi makanan/minuman."
    },
    {
      id: "cast_2",
      castNumber: "2",
      characterName: "Barista",
      actorName: "Dimas Anggara",
      role: "Featured Talent",
      phone: "+62 812-9876-5432",
      pickupTime: "06:00 AM",
      hmuTime: "06:30 AM",
      onSetTime: "07:30 AM",
      notes: "Sudah latihan pouring V60 bersama barista konsultan."
    },
    {
      id: "cast_3",
      castNumber: "3",
      characterName: "Office Co-workers (3x)",
      actorName: "Talent Agency Pool",
      role: "Supporting & Extras",
      phone: "+62 813-5555-1212 (PIC Agensi)",
      pickupTime: "11:30 AM",
      hmuTime: "12:15 PM",
      onSetTime: "13:30 PM",
      notes: "Standby di Holding Room 2 lantai 2."
    }
  ],
  crew: [
    { id: "cr_1", department: "Direction", role: "Director", name: "Arya Pratama", phone: "+62 811-1000-001", callTime: "06:00 AM" },
    { id: "cr_2", department: "Direction", role: "1st Assistant Director (1st AD)", name: "Budi Santoso", phone: "+62 811-1000-002", callTime: "05:30 AM" },
    { id: "cr_3", department: "Direction", role: "Script Supervisor", name: "Siti Rahma", phone: "+62 811-1000-003", callTime: "06:00 AM" },
    { id: "cr_4", department: "Production", role: "Executive Producer", name: "Maya Siregar", phone: "+62 811-2000-001", callTime: "06:00 AM" },
    { id: "cr_5", department: "Production", role: "Unit Production Manager (UPM)", name: "Andi Wijaya", phone: "+62 811-2000-002", callTime: "05:00 AM" },
    { id: "cr_6", department: "Camera", role: "Director of Photography (DoP)", name: "Reza Rahardian", phone: "+62 811-3000-001", callTime: "06:00 AM" },
    { id: "cr_7", department: "Camera", role: "1st AC / Focus Puller", name: "Eko Prasetyo", phone: "+62 811-3000-002", callTime: "05:45 AM" },
    { id: "cr_8", department: "Camera", role: "2nd AC / DIT / Data Wrangler", name: "Kevin Sanjaya", phone: "+62 811-3000-003", callTime: "05:45 AM" },
    { id: "cr_9", department: "Lighting & Grip", role: "Gaffer", name: "Hendro Wibowo", phone: "+62 811-4000-001", callTime: "05:00 AM" },
    { id: "cr_10", department: "Lighting & Grip", role: "Key Grip", name: "Joko Susilo", phone: "+62 811-4000-002", callTime: "05:00 AM" },
    { id: "cr_11", department: "Sound", role: "Location Sound Recordist", name: "Fajar Nugraha", phone: "+62 811-5000-001", callTime: "06:00 AM" },
    { id: "cr_12", department: "Art Department", role: "Art Director", name: "Dian Sastrowardoyo", phone: "+62 811-6000-001", callTime: "05:00 AM" },
    { id: "cr_13", department: "Wardrobe & MUA", role: "Wardrobe Stylist", name: "Nadia Utami", phone: "+62 811-7000-001", callTime: "06:00 AM" },
    { id: "cr_14", department: "Wardrobe & MUA", role: "Key Makeup Artist", name: "Putri Ayu", phone: "+62 811-7000-002", callTime: "06:00 AM" }
  ],
  equipment: [
    { id: "eq_1", category: "Camera", item: "ARRI Alexa Mini LF + Cage Kit", qty: "1 set", status: "Checked / Ready", source: "Rental (CineRent Jkt)" },
    { id: "eq_2", category: "Camera", item: "Sony FX3 (B-Cam Gimbal Rig)", qty: "1 unit", status: "Checked / Ready", source: "In-House" },
    { id: "eq_3", category: "Lenses", item: "Cooke Anamorphic /i Prime Set (25, 32, 50, 75, 100mm)", qty: "5 lenses", status: "Checked / Ready", source: "Rental" },
    { id: "eq_4", category: "Lenses", item: "Canon 100mm f/2.8L Macro IS USM", qty: "1 lens", status: "Checked / Ready", source: "Rental" },
    { id: "eq_5", category: "Grip & Support", item: "DJI Ronin 2 3-Axis Gimbal + Ready Rig", qty: "1 set", status: "Checked / Ready", source: "Rental" },
    { id: "eq_6", category: "Grip & Support", item: "Dana Dolly Kit 6ft Rails + 2x Combo Stands", qty: "1 set", status: "Checked / Ready", source: "In-House" },
    { id: "eq_7", category: "Lighting", item: "Aputure LS 600d Pro + F10 Fresnel", qty: "2 units", status: "Checked / Ready", source: "Rental" },
    { id: "eq_8", category: "Lighting", item: "Aputure LS 300x Bi-Color + Light Dome", qty: "2 units", status: "Checked / Ready", source: "In-House" },
    { id: "eq_9", category: "Lighting", item: "Nanlite Pavotube II 30X RGB Tubes", qty: "4 tubes", status: "Checked / Ready", source: "Rental" },
    { id: "eq_10", category: "Sound", item: "Sound Devices 833 8-Channel Mixer/Recorder", qty: "1 unit", status: "Checked / Ready", source: "Rental" },
    { id: "eq_11", category: "Sound", item: "Sennheiser MKH 416 Boom Mic + Pole & Blimp", qty: "1 set", status: "Checked / Ready", source: "In-House" },
    { id: "eq_12", category: "Power & Utility", item: "Genset Silent 20 kVA + Rubber Power Cable Box", qty: "1 unit", status: "Checked / Ready", source: "Rental" }
  ],
  daySchedule: [
    { time: "05:00 AM", activity: "Loading In & Genset Setup (Grip & Lighting & Art)" },
    { time: "06:00 AM", activity: "General Crew Call & Hot Breakfast / Coffee" },
    { time: "06:30 AM", activity: "Cast 2 (Barista) Arrives - Wardrobe & Makeup" },
    { time: "07:00 AM", activity: "Cast 1 (Sarah) Arrives - Wardrobe & Makeup" },
    { time: "07:30 AM", activity: "Block & Light Scene 1 (INT. Roastery)" },
    { time: "08:15 AM", activity: "SHOOT Scene 1 (Shots 1A, 1B, 1C)" },
    { time: "11:30 AM", activity: "Wrap Scene 1 & Company Move to Sidewalk" },
    { time: "12:00 PM", activity: "LUNCH BREAK (Catering Menu A & B, Halal)" },
    { time: "13:00 PM", activity: "Block & Light Scene 2 (EXT. Sidewalk Tracking)" },
    { time: "13:45 PM", activity: "SHOOT Scene 2 (Shots 2A, 2B)" },
    { time: "16:15 PM", activity: "Wrap Scene 2 & Move to Studio 4 (Office Set)" },
    { time: "17:00 PM", activity: "Block & Light Scene 3 (INT. Office)" },
    { time: "17:45 PM", activity: "SHOOT Scene 3 (Shots 3A, 3B)" },
    { time: "20:00 PM", activity: "ESTIMATED WRAP DAY 1 - Data Backup & DIT Sign-off" }
  ],
  departmentNotes: {
    production: "Semua kru wajib memakai ID badge produksi. Parkir khusus Gate B. Katering disiapkan 35 porsi per sesi.",
    camera: "Data wrangler wajib backup 3 salinan: 2x Rugged SSD + 1x LTO/Cloud backup harian sebelum wrap.",
    lighting: "Distribusi kabel di area trotoar wajib diberi rubber ramp pelindung agar aman bagi pejalan kaki.",
    sound: "Trotoar Senopati ada potensi kebisingan knalpot kendaraan. Gunakan wireless lav mikrofon tersembunyi + boom backup.",
    art: "Pastikan cup kopi mockup bersih dan label logo Aura menghadap tepat ke arah kamera.",
    wardrobe: "Sediakan cadangan 1 set kemeja Sarah jika terkena tumpahan noda kopi saat take."
  }
};
